services:
  database:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - 3366:3306
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_DATABASE=crypto_market
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  server:
    container_name: laravel-api
    image: laravel-api-prod:1.0.0
    build:
      context: ./server
      dockerfile: Dockerfile
      target: php
    working_dir: /var/www
    volumes:
      - "./server:/var/www"
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=crypto_market
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_ROOT_PASSWORD=password
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  client:
    container_name: flutter-ui
    image: flutter-ui-prod:1.0.0
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: "/home/dev"
    depends_on:
      - server
    volumes:
      - "./client:/home/dev"
    ports:
      - "8080:80"

volumes:
  db-data: ~
